# Importing Libraries

In [ ]:
import math as ma
import numpy as np

# Taking input from the user for writing a matrix


In [ ]:
# a linear vector
n=int(input('Please tell the number of entries 1 D array:'))
a=np.array([int(input('Number:' )) for i in range(n)])

In [ ]:
# a square matrix
n=int(input('Please tell the number of columns in your square matrix: '))
q=np.zeros((n,n))
for i in range(n):
    for j in range(n):
        q[i][j]=int(input('Number:'))
print('Your Input Matrix is:', q)

# Matrix multipication:

In [ ]:
np.dot(a,q)# dot product of two matrix

In [ ]:
a*q     #Elementwise multi plication

# Creating a function

In [ ]:
## Creating a function
def add(a,b):
    return a+b
def subtract(a,b):
    return a-b


In [ ]:
## Calling a function

print(add(4,5))
print(subtract(4,6))

In [ ]:
#Geneating a linear vector on length n
n=int(input('Please tell the number of entries 1 D array:'))
def linvec(n):
    a=np.array([int(input()) for i in range(n)])
    return a
b=linvec(n)
print('Shape of the given vector is',b.shape) #(size of the vecore)

In [ ]:
# Generating a square matrix of size n
n=int(input('Please tell the number of columns in your square matrix: '))
def squaremat(n):
    q=np.zeros((n,n))   ## generate a matrix of size n*n with zeros
    for i in range(n):
        for j in range(n):
            q[i][j]=int(input('Number at (%d,%d):' % (int(i+1),int(j+1))))
    return q
a=squaremat(n)

print('Shape of the given matrix is',a.shape) # size of the matrix

In [ ]:
def matrixmult(a,b):
    return np.dot(a,b)

In [ ]:
def elemntwisemult(a,b):
    return a*b

In [ ]:
matrixmult(a,q)

In [ ]:
elemntwisemult(a,q)

In [ ]:
#Multiplying with transpose
matrixmult(q.T,a) # b.T gives the transpose of the matrix b


# Simple bar problem using above concepts:

In [ ]:
# Learning how to make a pseudo code:

In [ ]:
# from PIL import Image
# myImage = Image.open('FEM problem.JPG');
# myImage.show()

In [ ]:
# Taking inputs from the user:

In [ ]:
# Accepting inputs from the user
ele=int(input('Number of elements in your problem:',))
nodes=int(input('Number of nodes in your problem:',))
n=int(input('Number of Fixed Nodes '))
fix_n=np.array([int(input('Node number (Please fixed provide nodes in increasing order) ')) for i in range(n)])
dof_per_node=int(input('Degrees of freedom per node '))
C=np.zeros((ele,2*dof_per_node))
for i in range(ele):
    C[i][0]=int(input('First node of element %d ' % int(i+1) ))
    C[i][1]=int(input('Last node of element %d ' % int(i+1) ))

In [ ]:
A=np.zeros(ele)
E=np.zeros(ele)
l=np.zeros(ele)
k=np.zeros((ele,2*dof_per_node,2*dof_per_node))
F=np.zeros(nodes*dof_per_node)
for i in range(ele):
    A[i]=float(input("Area of element %d " % int(i+1)))
    E[i]=float(input("Modulus of elasticity of element %d " % int(i+1)))
    l[i]=float(input("Length of element %d " % int(i+1)))
    k[i]=float(A[i]*E[i]/l[i])*np.array([[1,-1],[-1,1]]).astype(np.float)  ### Creating local stiffness matrix 
for i in range(nodes):
    F[i]=float(input("Load at node %d is " % int(i+1)))

In [ ]:
# Assembling global stiffness matrix

K = np.zeros((nodes*dof_per_node,nodes*dof_per_node))  

for i in range(ele):
    ind1=C[i]-1
    ind1=ind1.astype(int)
    K[ind1[0],ind1[0]]+=k[i][0][0]
    K[ind1[1],ind1[0]]+=k[i][1][0]
    K[ind1[0],ind1[1]]+=k[i][0][1]
    K[ind1[1],ind1[1]]+=k[i][1][1]
K1=K.copy()
K_temp1=K1

In [ ]:
K

In [ ]:
# applying boundary conditions
for i in fix_n:
    K_temp1[i-1][:] = 0
    K_temp1.T[:][i-1] = 0
# Select non-zero rows
K_temp1 = K_temp1[~np.all(K_temp1 == 0, axis=1)]
# Select non-zero columns
K_temp1 = K_temp1[:, ~np.all(K_temp1 == 0, axis=0)]
F_temp1 = np.delete(F, list(fix_n-1))

In [ ]:
# Solve for available values
x = np.linalg.solve(K_temp1,F_temp1)
u=np.zeros(nodes*dof_per_node)
A= [i for i in range(nodes) if i not in list(fix_n-1)]
u[A]=x
sigma=np.zeros(ele)
for i in range(ele):
    ind1=C[i]-1
    ind1=ind1.astype(int)
    sigma[i]=(u[ind1[1]]-u[ind1[0]])/l[i]*E[i]

In [ ]:
x

In [ ]:
sigma

In [ ]:
R=np.dot(K,u)-F

In [ ]:
print('The global stiffness matrix is ',K)
print('The nodal displacements are ',u)
print('The elemental stresses are ',sigma)
print('The reactions at the nodes are ', R)

In [ ]:
ele=int(input('Number of elements in your problem:',))
nodes=int(input('Number of nodes in your problem:',))
n=int(input('Number of Fixed Nodes '))
fix_n=np.array([int(input('Node number (Please provide fixed nodes in increasing order) ')) for i in range(n)])
dof_per_node=int(input('Degrees of freedom per node '))
C=np.zeros((ele,2*dof_per_node))
for i in range(ele):
    C[i][0]=int(input('First node of element %d ' % int(i+1) ))
    C[i][1]=int(input('Last node of element %d ' % int(i+1) ))
    
def barelements(ele,nodes,n,fix_n,C):
    A=np.zeros(ele)
    E=np.zeros(ele)
    l=np.zeros(ele)
    k=np.zeros((ele,2*dof_per_node,2*dof_per_node))
    F=np.zeros(nodes*dof_per_node)
    for i in range(ele):
        A[i]=float(input("Area of element %d :" % int(i+1)))
        E[i]=float(input("Modulus of elasticity of element %d :" % int(i+1)))
        l[i]=float(input("Length of element %d :" % int(i+1)))
        k[i]=float(A[i]*E[i]/l[i])*np.array([[1,-1],[-1,1]]).astype(np.float)
    for i in range(nodes):
        F[i]=float(input("Load at node %d is :" % int(i+1)))
    ## construct global mass and stiffness matrices
    # K = np.zeros((ele*dof_per_node,ele*dof_per_node))
    # assembly of elements
    K = np.zeros((nodes*dof_per_node,nodes*dof_per_node))

    for i in range(ele):
        ind1=C[i]-1
        ind1=ind1.astype(int)
        K[ind1[0],ind1[0]]+=k[i][0][0]
        K[ind1[1],ind1[0]]+=k[i][1][0]
        K[ind1[0],ind1[1]]+=k[i][0][1]
        K[ind1[1],ind1[1]]+=k[i][1][1]
    K1=K.copy()
    K_temp1=K1
    for i in fix_n:
        K_temp1[i-1][:] = 0
        K_temp1.T[:][i-1] = 0
    # Select non-zero rows
    K_temp1 = K_temp1[~np.all(K_temp1 == 0, axis=1)]
    # Select non-zero columns
    K_temp1 = K_temp1[:, ~np.all(K_temp1 == 0, axis=0)]
    F_temp1 = np.delete(F, list(fix_n-1))
    x = np.linalg.solve(K_temp1,F_temp1)
    u=np.zeros(nodes)
    t= [i for i in range(nodes) if i not in list(fix_n-1)]
    u[t]=x
    sigma=np.zeros(ele)
    for i in range(ele):
        sigma[i]=(u[i+1]-u[i])/l[i]*E[i]
    R=np.dot(K,u)-F
    
    
    print('The global stiffness matrix is ',K)
    print('The nodal displacements are ',u)
    print('The elemental stresses are ',sigma)
    print('The reactions at the nodes are ', R)
    
    return 




In [ ]:
barelements(ele,nodes,n,fix_n,C)

# Updating code for 2D condition

In [1]:
import numpy as np
import math as ma

In [3]:

##### Adding codes for 2D elements

ele=int(input('Number of elements in your problem:',))
nodes=int(input('Number of nodes in your problem:',))
n=int(input('Number of Fixed Nodes '))
fix_n=np.array([int(input('Node number (Please provide fixed nodes in increasing order) ')) for i in range(n)])
dof_per_node=int(input('Degrees of freedom per node '))
C=np.zeros((ele,2))
for i in range(ele):
    C[i][0]=int(input('First node of element %d ' % int(i+1) ))
    C[i][1]=int(input('Last node of element %d ' % int(i+1) ))
    

A=np.zeros(ele)
E=np.zeros(ele)
l=np.zeros(ele)
k=np.zeros((ele,2*dof_per_node,2*dof_per_node))
F=np.zeros(nodes*dof_per_node)
theta=np.zeros(ele)
for i in range(ele):
    A[i]=float(input("Area of element %d :" % int(i+1)))
    E[i]=float(input("Modulus of elasticity of element %d :" % int(i+1)))
    l[i]=float(input("Length of element %d :" % int(i+1)))
    if dof_per_node>=1:
        theta[i]=float(input("Inclination of element (in degrees) %d :" % int(i+1)))
        
for i in range(ele):
    if dof_per_node==1:
        k[i]=float(A[i]*E[i]/l[i])*np.array([[1,-1],[-1,1]]).astype(np.float)
    if dof_per_node==2:
        k[i]=float(A[i]*E[i]/l[i])*np.array([[ma.cos(ma.pi*theta[i]/180)**2,ma.cos(ma.pi*theta[i]/180)*ma.sin(ma.pi*theta[i]/180),-1*ma.cos(ma.pi*theta[i]/180)**2,-ma.cos(ma.pi*theta[i]/180)*ma.sin(ma.pi*theta[i]/180)],
                                             [ma.cos(ma.pi*theta[i]/180)*ma.sin(ma.pi*theta[i]/180),ma.sin(ma.pi*theta[i]/180)**2,-ma.cos(ma.pi*theta[i]/180)*ma.sin(ma.pi*theta[i]/180),-ma.sin(ma.pi*theta[i]/180)**2],
                                             [-ma.cos(ma.pi*theta[i]/180)**2,-ma.cos(ma.pi*theta[i]/180)*ma.sin(ma.pi*theta[i]/180),ma.cos(ma.pi*theta[i]/180)**2,ma.cos(ma.pi*theta[i]/180)*ma.sin(ma.pi*theta[i]/180)],
                                             [-ma.cos(ma.pi*theta[i]/180)*ma.sin(ma.pi*theta[i]/180),-ma.sin(ma.pi*theta[i]/180)**2,ma.cos(ma.pi*theta[i]/180)*ma.sin(ma.pi*theta[i]/180),ma.sin(ma.pi*theta[i]/180)**2]]).astype(np.float)
        


Number of elements in your problem:3
Number of nodes in your problem:4
Number of Fixed Nodes 3
Node number (Please provide fixed nodes in increasing order) 1
Node number (Please provide fixed nodes in increasing order) 2
Node number (Please provide fixed nodes in increasing order) 3
Degrees of freedom per node 2
First node of element 1 1
Last node of element 1 4
First node of element 2 2
Last node of element 2 4
First node of element 3 3
Last node of element 3 4
Area of element 1 :1
Modulus of elasticity of element 1 :10e5
Length of element 1 :1
Inclination of element (in degrees) 1 :-30
Area of element 2 :1
Modulus of elasticity of element 2 :1e6
Length of element 2 :1
Inclination of element (in degrees) 2 :30
Area of element 3 :1
Modulus of elasticity of element 3 :1e6
Length of element 3 :1.322
Inclination of element (in degrees) 3 :49.1


In [5]:
k.shape

(3, 4, 4)

In [7]:
# assembly of Glbal stiffness matrix
K_global = np.zeros((nodes*dof_per_node,nodes*dof_per_node))


if dof_per_node==1:
    for i in range(ele):
        ind1=C[i]-1
        ind1=ind1.astype(int)
        K[ind1[0],ind1[0]]+=k[i][0][0]
        K[ind1[1],ind1[0]]+=k[i][1][0]
        K[ind1[0],ind1[1]]+=k[i][0][1]
        K[ind1[1],ind1[1]]+=k[i][1][1]
if dof_per_node==2:
    for e in range(ele):
        # Get the nodes for this element
        node = C[e]
        node=node.astype(int)
        node=node-1
        # Loop over each node in the element
        for i in range(len(node)):
            # Loop over each degree of freedom for node i
            for j in range(2):
                # Loop over each node in the element
                for b in range(len(node)):
                    # Loop over each degree of freedom for node k
                    for o in range(2):
                        # Add the corresponding element stiffness matrix term to the global stiffness matrix
                        K_global[2*node[i]+j, 2*node[b]+o] += k[e][2*i+j, 2*b+o]


In [8]:
K_global

array([[ 750000.        , -433012.70189222,       0.        ,
              0.        ,       0.        ,       0.        ,
        -750000.        ,  433012.70189222],
       [-433012.70189222,  250000.        ,       0.        ,
              0.        ,       0.        ,       0.        ,
         433012.70189222, -250000.        ],
       [      0.        ,       0.        ,  750000.        ,
         433012.70189222,       0.        ,       0.        ,
        -750000.        , -433012.70189222],
       [      0.        ,       0.        ,  433012.70189222,
         250000.        ,       0.        ,       0.        ,
        -433012.70189222, -250000.        ],
       [      0.        ,       0.        ,       0.        ,
              0.        ,  324270.44867416,  374348.04497269,
        -324270.44867416, -374348.04497269],
       [      0.        ,       0.        ,       0.        ,
              0.        ,  374348.04497269,  432159.2033682 ,
        -374348.04497269, -4321

In [6]:
C

array([[1., 4.],
       [2., 4.],
       [3., 4.]])

In [9]:
#### Applying Boundary Conditions

K=K_global
K1=K.copy()
K_temp1=K1
if dof_per_node==1:
    for i in fix_n:
        print(i)
        K_temp1[i-1][:] = 0
        print(K_temp1)
        K_temp1.T[:][i-1] = 0
        print(K_temp1)

    # Select non-zero rows
    K_temp1 = K_temp1[~np.all(K_temp1 == 0, axis=1)]
    # Select non-zero columns
    K_temp1 = K_temp1[:, ~np.all(K_temp1 == 0, axis=0)]
    
if dof_per_node==2:
    for i in fix_n-1:
        print(i)
        K_temp1[2*i][:] = 0
        K_temp1[2*i+1][:] = 0
        print(K_temp1)
        K_temp1.T[:][2*i] = 0
        K_temp1.T[:][2*i+1] = 0
        print(K_temp1)
   

# Select non-zero rows
K_temp1 = K_temp1[~np.all(K_temp1 == 0, axis=1)]
#Select non-zero columns
K_temp1 = K_temp1[:, ~np.all(K_temp1 == 0, axis=0)]



0
[[      0.               0.               0.               0.
        0.               0.               0.               0.        ]
 [      0.               0.               0.               0.
        0.               0.               0.               0.        ]
 [      0.               0.          750000.          433012.70189222
        0.               0.         -750000.         -433012.70189222]
 [      0.               0.          433012.70189222  250000.
        0.               0.         -433012.70189222 -250000.        ]
 [      0.               0.               0.               0.
   324270.44867416  374348.04497269 -324270.44867416 -374348.04497269]
 [      0.               0.               0.               0.
   374348.04497269  432159.2033682  -374348.04497269 -432159.2033682 ]
 [-750000.          433012.70189222 -750000.         -433012.70189222
  -324270.44867416 -374348.04497269 1824270.44867416  374348.04497269]
 [ 433012.70189222 -250000.         -433012.7018922

In [10]:
K_temp1

array([[1824270.44867416,  374348.04497269],
       [ 374348.04497269,  932159.2033682 ]])

In [11]:
### Accepting force
F=np.zeros(nodes*dof_per_node)
for i in range(nodes):
    for j in range(dof_per_node):
        F[2*i+j]=float(input("Load at node %d and dof %d is :" % (int(i+1),int(j+1))))
F

Load at node 1 and dof 1 is :0
Load at node 1 and dof 2 is :0
Load at node 2 and dof 1 is :0
Load at node 2 and dof 2 is :0
Load at node 3 and dof 1 is :0
Load at node 3 and dof 2 is :0
Load at node 4 and dof 1 is :10e3
Load at node 4 and dof 2 is :0


array([    0.,     0.,     0.,     0.,     0.,     0., 10000.,     0.])

In [12]:
## 
if dof_per_node==1:
    F_temp1 = np.delete(F, list(fix_n-1))#Deleeting fixed nodes entires
if dof_per_node==2:
    F_temp1 = np.delete(F, np.array((2*(fix_n-1),2*np.array(fix_n-1)+1))) #Deleeting fixed nodes entries

In [13]:
F_temp1

array([10000.,     0.])

In [14]:
## Solving for availabel degrees of freedom
x = np.linalg.solve(K_temp1,F_temp1)
u=np.zeros(nodes*dof_per_node)

g= [i for i in range(nodes) if i not in list(fix_n-1)]
v=0
for i in g:
    for j in range(len(x)-1):
        u[2*i]=x[j]
        u[2*i+1]=x[j+1]

In [16]:
u

array([ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.00597395, -0.00239909])

In [17]:
### Finding eleemntal quantities

if dof_per_node==1:
    sigma=np.zeros(ele)
    for i in range(ele):
        sigma[i]=(u[i+1]-u[i])/l[i]*E[i]
    R=np.dot(K,u)-F
    
###### Transfroming global findings to local settings to find elemental, deformations, stresses and loads
if dof_per_node==2:
    #finding displacement in local co-ordiates:
    u_loc=np.zeros((ele,2*dof_per_node))
    u_ele=np.zeros((ele,2*dof_per_node))
    for i in range(ele):
        u_loc_tran=np.array([[ma.cos(ma.pi*theta[i]/180),ma.sin(ma.pi*theta[i]/180),0,0],
                        [-ma.sin(ma.pi*theta[i]/180),ma.cos(ma.pi*theta[i]/180),0,0],
                       [0,0,ma.cos(ma.pi*theta[i]/180),ma.sin(ma.pi*theta[i]/180)],
                        [0,0,-ma.sin(ma.pi*theta[i]/180),ma.cos(ma.pi*theta[i]/180)]])
        nd=C[i]-1
        nd=nd.astype(int)
        v=0
        for j in nd:
            u_ele[i][2*v]=u[2*j]
            u_ele[i][2*v+1]=u[2*j+1]
            v+=1
        print(u_ele[i])
        u_loc[i]=np.dot(u_loc_tran,u_ele[i])


    
    


[ 0.          0.          0.00597395 -0.00239909]
[ 0.          0.          0.00597395 -0.00239909]
[ 0.          0.          0.00597395 -0.00239909]


In [18]:
## Elemetnal forces
F_ele=np.zeros((ele,2*dof_per_node))
for i in range(ele):
    f_trans=float(A[i]*E[i]/l[i])*np.array([[1,0,-1,0],[0,0,0,0],[-1,0,1,0],[0,0,0,0]]).astype(np.float)
    F_ele[i]=np.dot(f_trans,u_loc[i])
    


In [19]:
60.2/4.908


12.265688671556642

In [20]:
### Reactions at the support
R=np.dot(K,u)-F

In [24]:
R

array([-5.51929758e+03,  3.18656795e+03, -3.44162319e+03, -1.98702207e+03,
       -1.03907923e+03, -1.19954587e+03,  0.00000000e+00, -4.54747351e-13])

In [21]:
u

array([ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.00597395, -0.00239909])

In [22]:
u_loc

array([[ 0.        ,  0.        ,  0.00637314,  0.0009093 ],
       [ 0.        ,  0.        ,  0.00397404, -0.00506465],
       [ 0.        ,  0.        ,  0.00209803, -0.00608621]])

In [23]:
C[1]

array([2., 4.])

In [ ]:
# Assembling whole code
import numpy as np
import math as ma
ele=int(input('Number of elements in your problem:',))
nodes=int(input('Number of nodes in your problem:',))
n=int(input('Number of Fixed Nodes '))
fix_n=np.array([int(input('Node number (Please provide fixed nodes in increasing order) ')) for i in range(n)])
dof_per_node=int(input('Degrees of freedom per node '))
C=np.zeros((ele,2))
for i in range(ele):
    C[i][0]=int(input('First node of element %d ' % int(i+1) ))
    C[i][1]=int(input('Last node of element %d ' % int(i+1) ))
def solver1D2D(ele,nodes,n,fix_n,dof_per_node,C):
    A=np.zeros(ele)
    E=np.zeros(ele)
    l=np.zeros(ele)
    k=np.zeros((ele,2*dof_per_node,2*dof_per_node))
    F=np.zeros(nodes*dof_per_node)
    theta=np.zeros(ele)
    for i in range(ele):
        A[i]=float(input("Area of element %d :" % int(i+1)))
        E[i]=float(input("Modulus of elasticity of element %d :" % int(i+1)))
        l[i]=float(input("Length of element %d :" % int(i+1)))
        if dof_per_node>=1:
            theta[i]=float(input("Inclination of element (in degrees) %d :" % int(i+1)))
    for i in range(nodes):
        for j in range(dof_per_node):
            F[2*i+j]=float(input("Load at node %d and dof %d is :" % (int(i+1),int(j+1))))

    for i in range(ele):
        if dof_per_node==1:
            k[i]=float(A[i]*E[i]/l[i])*np.array([[1,-1],[-1,1]]).astype(np.float)
        if dof_per_node==2:
            k[i]=float(A[i]*E[i]/l[i])*np.array([[ma.cos(ma.pi*theta[i]/180)**2,ma.cos(ma.pi*theta[i]/180)*ma.sin(ma.pi*theta[i]/180),-1*ma.cos(ma.pi*theta[i]/180)**2,-ma.cos(ma.pi*theta[i]/180)*ma.sin(ma.pi*theta[i]/180)],
                                                 [ma.cos(ma.pi*theta[i]/180)*ma.sin(ma.pi*theta[i]/180),ma.sin(ma.pi*theta[i]/180)**2,-ma.cos(ma.pi*theta[i]/180)*ma.sin(ma.pi*theta[i]/180),-ma.sin(ma.pi*theta[i]/180)**2],
                                                 [-ma.cos(ma.pi*theta[i]/180)**2,-ma.cos(ma.pi*theta[i]/180)*ma.sin(ma.pi*theta[i]/180),ma.cos(ma.pi*theta[i]/180)**2,ma.cos(ma.pi*theta[i]/180)*ma.sin(ma.pi*theta[i]/180)],
                                                 [-ma.cos(ma.pi*theta[i]/180)*ma.sin(ma.pi*theta[i]/180),-ma.sin(ma.pi*theta[i]/180)**2,ma.cos(ma.pi*theta[i]/180)*ma.sin(ma.pi*theta[i]/180),ma.sin(ma.pi*theta[i]/180)**2]]).astype(np.float)
    # assembly of elements
    K_global = np.zeros((nodes*dof_per_node,nodes*dof_per_node))


    if dof_per_node==1:
        for i in range(ele):
            ind1=C[i]-1
            ind1=ind1.astype(int)
            K[ind1[0],ind1[0]]+=k[i][0][0]
            K[ind1[1],ind1[0]]+=k[i][1][0]
            K[ind1[0],ind1[1]]+=k[i][0][1]
            K[ind1[1],ind1[1]]+=k[i][1][1]
    if dof_per_node==2:
        for e in range(ele):
            # Get the nodes for this element
            node = C[e]
            node=node.astype(int)
            node=node-1
            # Loop over each node in the element
            for i in range(len(node)):
                # Loop over each degree of freedom for node i
                for j in range(2):
                    # Loop over each node in the element
                    for b in range(len(node)):
                        # Loop over each degree of freedom for node k
                        for o in range(2):
                            # Add the corresponding element stiffness matrix term to the global stiffness matrix
                            K_global[2*node[i]+j, 2*node[b]+o] += k[e][2*i+j, 2*b+o]

    K=K_global
    K1=K.copy()
    K_temp1=K1
    if dof_per_node==1:
        for i in fix_n:
            print(i)
            K_temp1[i-1][:] = 0
            print(K_temp1)
            K_temp1.T[:][i-1] = 0
            print(K_temp1)

        # Select non-zero rows
        K_temp1 = K_temp1[~np.all(K_temp1 == 0, axis=1)]
        # Select non-zero columns
        K_temp1 = K_temp1[:, ~np.all(K_temp1 == 0, axis=0)]

    if dof_per_node==2:
        for i in fix_n-1:
            K_temp1[2*i][:] = 0
            K_temp1[2*i+1][:] = 0
            K_temp1.T[:][2*i] = 0
            K_temp1.T[:][2*i+1] = 0

    # Select non-zero rows
    K_temp1 = K_temp1[~np.all(K_temp1 == 0, axis=1)]
    #Select non-zero columns
    K_temp1 = K_temp1[:, ~np.all(K_temp1 == 0, axis=0)]


    if dof_per_node==1:
        F_temp1 = np.delete(F, list(fix_n-1))#Deleeting fixed nodes entires
    if dof_per_node==2:
        F_temp1 = np.delete(F, np.array((2*(fix_n-1),2*np.array(fix_n-1)+1))) #Deleeting fixed nodes entries
    x = np.linalg.solve(K_temp1,F_temp1)
    u=np.zeros(nodes*dof_per_node)

    # if dof_per_node==2:
    g= [i for i in range(nodes) if i not in list(fix_n-1)]
    for i in g:
        for j in range(len(x)-1):
            u[2*i]=x[j]
            u[2*i+1]=x[j+1]
    if dof_per_node==1:
        sigma=np.zeros(ele)
        for i in range(ele):
            sigma[i]=(u[i+1]-u[i])/l[i]*E[i]
        R=np.dot(K,u)-F



    if dof_per_node==2:
        #finding displacement in local co-ordiates:
        u_loc=np.zeros((ele,2*dof_per_node))
        u_ele=np.zeros((ele,2*dof_per_node))
        for i in range(ele):
            u_loc_tran=np.array([[ma.cos(ma.pi*theta[i]/180),ma.sin(ma.pi*theta[i]/180),0,0],
                            [-ma.sin(ma.pi*theta[i]/180),ma.cos(ma.pi*theta[i]/180),0,0],
                           [0,0,ma.cos(ma.pi*theta[i]/180),ma.sin(ma.pi*theta[i]/180)],
                            [0,0,-ma.sin(ma.pi*theta[i]/180),ma.cos(ma.pi*theta[i]/180)]])
            nd=C[i]-1
            nd=nd.astype(int)
            v=0
            for j in nd:
                u_ele[i][2*v]=u[2*j]
                u_ele[i][2*v+1]=u[2*j+1]
                v+=1
            u_loc[i]=np.dot(u_loc_tran,u_ele[i])

    F_ele=np.zeros((ele,2*dof_per_node))
    for i in range(ele):
        f_trans=float(A[i]*E[i]/l[i])*np.array([[1,0,-1,0],[0,0,0,0],[-1,0,1,0],[0,0,0,0]]).astype(np.float)
        F_ele[i]=np.dot(f_trans,u_loc[i])
    R=np.dot(K,u)-F




    print('The global stiffness matrix is ',K_global)
    print('####################### \n ###################')
    print('Forces in the elements are ', F_ele)
    print('####################### \n ###################')
    print('The nodal displacements are ',u)
    print('####################### \n ###################')
    print('The reactions at the nodes are ', R)
    
    return

In [ ]:
solver1D2D(ele,nodes,n,fix_n,dof_per_node,C)