# Importing Libraries

In [15]:
import math as ma
import numpy as np

# Taking input from the user for writing a matrix


In [8]:
# a linear vector
n=int(input('Please tell the number of entries 1 D array:'))
a=np.array([int(input('Number:' )) for i in range(n)])

Please tell the number of entries 1 D array:2
Number:1
Number:1


In [9]:
# a square matrix
n=int(input('Please tell the number of columns in your square matrix: '))
q=np.zeros((n,n))
for i in range(n):
    for j in range(n):
        q[i][j]=int(input('Number:'))
print('Your Input Matrix is:', q)

Please tell the number of columns in your square matrix: 2
Number:1
Number:1
Number:1
Number:1
Your Input Matrix is: [[1. 1.]
 [1. 1.]]


# Matrix multipication:

In [11]:
np.dot(a,q)# dot product of two matrix

array([2., 2.])

In [12]:
a*q     #Elementwise multi plication

array([[1., 1.],
       [1., 1.]])

# Creating a function

In [13]:
## Creating a function
def add(a,b):
    return a+b
def subtract(a,b):
    return a-b


In [14]:
## Calling a function

print(add(4,5))
print(subtract(4,6))

9
-2


In [18]:
#Geneating a linear vector on length n
n=int(input('Please tell the number of entries 1 D array:'))
def linvec(n):
    a=np.array([int(input()) for i in range(n)])
    return a
b=linvec(n)
print('Shape of the given vector is',b.shape) #(size of the vecore)

Please tell the number of entries 1 D array:2
1
2
Shape of the given vector is (2,)


In [27]:
# Generating a square matrix of size n
n=int(input('Please tell the number of columns in your square matrix: '))
def squaremat(n):
    q=np.zeros((n,n))   ## generate a matrix of size n*n with zeros
    for i in range(n):
        for j in range(n):
            q[i][j]=int(input('Number at (%d,%d):' % (int(i+1),int(j+1))))
    return q
a=squaremat(n)

print('Shape of the given matrix is',a.shape) # size of the matrix

Please tell the number of columns in your square matrix: 2
Number at (1,1):1
Number at (1,2):1
Number at (2,1):1
Number at (2,2):1
Shape of the given matrix is (2, 2)


In [15]:
def matrixmult(a,b):
    return np.dot(a,b)

In [16]:
def elemntwisemult(a,b):
    return a*b

In [17]:
matrixmult(a,q)

array([2., 2.])

In [18]:
elemntwisemult(a,q)

array([[1., 1.],
       [1., 1.]])

In [20]:
#Multiplying with transpose
matrixmult(q.T,a) # b.T gives the transpose of the matrix b


array([2., 2.])

# Simple bar problem using above concepts:

In [23]:
# Learning how to make a pseudo code:

In [5]:
# from PIL import Image
# myImage = Image.open('FEM problem.JPG');
# myImage.show()

In [1]:
# Taking inputs from the user:

In [3]:
# Accepting inputs from the user
ele=int(input('Number of elements in your problem:',))
nodes=int(input('Number of nodes in your problem:',))
n=int(input('Number of Fixed Nodes '))
fix_n=np.array([int(input('Node number (Please fixed provide nodes in increasing order) ')) for i in range(n)])
dof_per_node=int(input('Degrees of freedom per node '))
C=np.zeros((ele,2*dof_per_node))
for i in range(ele):
    C[i][0]=int(input('First node of element %d ' % int(i+1) ))
    C[i][1]=int(input('Last node of element %d ' % int(i+1) ))

Number of elements in your problem:2
Number of nodes in your problem:3
Number of Fixed Nodes 2
Node number (Please fixed provide nodes in increasing order) 1
Node number (Please fixed provide nodes in increasing order) 3
Degrees of freedom per node 1
First node of element 
1 1
Last node of element 
1 2
First node of element 
2 2
Last node of element 
2 3


In [4]:
A=np.zeros(ele)
E=np.zeros(ele)
l=np.zeros(ele)
k=np.zeros((ele,2*dof_per_node,2*dof_per_node))
F=np.zeros(nodes*dof_per_node)
for i in range(ele):
    A[i]=float(input("Area of element %d " % int(i+1)))
    E[i]=float(input("Modulus of elasticity of element %d " % int(i+1)))
    l[i]=float(input("Length of element %d " % int(i+1)))
    k[i]=float(A[i]*E[i]/l[i])*np.array([[1,-1],[-1,1]]).astype(np.float)  ### Creating local stiffness matrix 
for i in range(nodes):
    F[i]=float(input("Load at node %d is " % int(i+1)))

Area of element 
1 1e-4
Modulus of elasticity of element 1 100e9
Length of element 
1 0.25
Area of element 
2 2e-4
Modulus of elasticity of element 2 100e9
Length of element 
2 0.4
Load at node 
1 is 0
Load at node 
2 is 10e3
Load at node 
3 is 0


In [5]:
# Assembling global stiffness matrix

K = np.zeros((nodes*dof_per_node,nodes*dof_per_node))  

for i in range(ele):
    ind1=C[i]-1
    ind1=ind1.astype(int)
    K[ind1[0],ind1[0]]+=k[i][0][0]
    K[ind1[1],ind1[0]]+=k[i][1][0]
    K[ind1[0],ind1[1]]+=k[i][0][1]
    K[ind1[1],ind1[1]]+=k[i][1][1]
K1=K.copy()
K_temp1=K1

In [6]:
K

array([[ 40000000., -40000000.,         0.],
       [-40000000.,  90000000., -50000000.],
       [        0., -50000000.,  50000000.]])

In [7]:
# applying boundary conditions
for i in fix_n:
    K_temp1[i-1][:] = 0
    K_temp1.T[:][i-1] = 0
# Select non-zero rows
K_temp1 = K_temp1[~np.all(K_temp1 == 0, axis=1)]
# Select non-zero columns
K_temp1 = K_temp1[:, ~np.all(K_temp1 == 0, axis=0)]
F_temp1 = np.delete(F, list(fix_n-1))

In [8]:
# Solve for available values
x = np.linalg.solve(K_temp1,F_temp1)
u=np.zeros(nodes*dof_per_node)
A= [i for i in range(nodes) if i not in list(fix_n-1)]
u[A]=x
sigma=np.zeros(ele)
for i in range(ele):
    ind1=C[i]-1
    ind1=ind1.astype(int)
    sigma[i]=(u[ind1[1]]-u[ind1[0]])/l[i]*E[i]

In [9]:
x

array([0.00011111])

In [10]:
sigma

array([ 44444444.44444445, -27777777.77777778])

In [11]:
R=np.dot(K,u)-F

In [12]:
print('The global stiffness matrix is ',K)
print('The nodal displacements are ',u)
print('The elemental stresses are ',sigma)
print('The reactions at the nodes are ', R)

The global stiffness matrix is  [[ 40000000. -40000000.         0.]
 [-40000000.  90000000. -50000000.]
 [        0. -50000000.  50000000.]]
The nodal displacements are  [0.         0.00011111 0.        ]
The elemental stresses are  [ 44444444.44444445 -27777777.77777778]
The reactions at the nodes are  [-4444.44444444     0.         -5555.55555556]


In [31]:
ele=int(input('Number of elements in your problem:',))
nodes=int(input('Number of nodes in your problem:',))
n=int(input('Number of Fixed Nodes '))
fix_n=np.array([int(input('Node number (Please provide fixed nodes in increasing order) ')) for i in range(n)])
dof_per_node=int(input('Degrees of freedom per node '))
C=np.zeros((ele,2*dof_per_node))
for i in range(ele):
    C[i][0]=int(input('First node of element %d ' % int(i+1) ))
    C[i][1]=int(input('Last node of element %d ' % int(i+1) ))
    
def barelements(ele,nodes,n,fix_n,C):
    A=np.zeros(ele)
    E=np.zeros(ele)
    l=np.zeros(ele)
    k=np.zeros((ele,2*dof_per_node,2*dof_per_node))
    F=np.zeros(nodes*dof_per_node)
    for i in range(ele):
        A[i]=float(input("Area of element %d :" % int(i+1)))
        E[i]=float(input("Modulus of elasticity of element %d :" % int(i+1)))
        l[i]=float(input("Length of element %d :" % int(i+1)))
        k[i]=float(A[i]*E[i]/l[i])*np.array([[1,-1],[-1,1]]).astype(np.float)
    for i in range(nodes):
        F[i]=float(input("Load at node %d is :" % int(i+1)))
    ## construct global mass and stiffness matrices
    # K = np.zeros((ele*dof_per_node,ele*dof_per_node))
    # assembly of elements
    K = np.zeros((nodes*dof_per_node,nodes*dof_per_node))

    for i in range(ele):
        ind1=C[i]-1
        ind1=ind1.astype(int)
        K[ind1[0],ind1[0]]+=k[i][0][0]
        K[ind1[1],ind1[0]]+=k[i][1][0]
        K[ind1[0],ind1[1]]+=k[i][0][1]
        K[ind1[1],ind1[1]]+=k[i][1][1]
    K1=K.copy()
    K_temp1=K1
    for i in fix_n:
        K_temp1[i-1][:] = 0
        K_temp1.T[:][i-1] = 0
    # Select non-zero rows
    K_temp1 = K_temp1[~np.all(K_temp1 == 0, axis=1)]
    # Select non-zero columns
    K_temp1 = K_temp1[:, ~np.all(K_temp1 == 0, axis=0)]
    F_temp1 = np.delete(F, list(fix_n-1))
    x = np.linalg.solve(K_temp1,F_temp1)
    u=np.zeros(nodes)
    t= [i for i in range(nodes) if i not in list(fix_n-1)]
    u[t]=x
    sigma=np.zeros(ele)
    for i in range(ele):
        sigma[i]=(u[i+1]-u[i])/l[i]*E[i]
    R=np.dot(K,u)-F
    
    
    print('The global stiffness matrix is ',K)
    print('The nodal displacements are ',u)
    print('The elemental stresses are ',sigma)
    print('The reactions at the nodes are ', R)
    
    return 




KeyboardInterrupt: Interrupted by user

In [258]:
barelements(ele,nodes,n,fix_n,C)

Area of element 
1 200
Modulus of elasticity of element 
1 200000
Length of element 
1 100
Area of element 
2 200
Modulus of elasticity of element 
2 200000
Length of element 
2 100
Area of element 
3 100
Modulus of elasticity of element 
3 200000
Length of element 
3 150
Load at node 
1 is 0
Load at node 
2 is 20000
Load at node 
3 is 0
Load at node 
4 is 10000
[0 1]
[1 2]
[2 3]


(array([0.   , 0.075, 0.1  , 0.175]),
 array([150.,  50., 100.]),
 array([-3.00000000e+04,  7.27595761e-12,  0.00000000e+00,  0.00000000e+00]),
 array([[ 400000.        , -400000.        ,       0.        ,
               0.        ],
        [-400000.        ,  800000.        , -400000.        ,
               0.        ],
        [      0.        , -400000.        ,  533333.33333333,
         -133333.33333333],
        [      0.        ,       0.        , -133333.33333333,
          133333.33333333]]))

# Updating code for 2D condition

In [71]:

##### Adding codes for 2D elements

ele=int(input('Number of elements in your problem:',))
nodes=int(input('Number of nodes in your problem:',))
n=int(input('Number of Fixed Nodes '))
fix_n=np.array([int(input('Node number (Please provide fixed nodes in increasing order) ')) for i in range(n)])
dof_per_node=int(input('Degrees of freedom per node '))
C=np.zeros((ele,2))
for i in range(ele):
    C[i][0]=int(input('First node of element %d ' % int(i+1) ))
    C[i][1]=int(input('Last node of element %d ' % int(i+1) ))
    

A=np.zeros(ele)
E=np.zeros(ele)
l=np.zeros(ele)
k=np.zeros((ele,2*dof_per_node,2*dof_per_node))
F=np.zeros(nodes*dof_per_node)
theta=np.zeros(ele)
for i in range(ele):
    A[i]=float(input("Area of element %d :" % int(i+1)))
    E[i]=float(input("Modulus of elasticity of element %d :" % int(i+1)))
    l[i]=float(input("Length of element %d :" % int(i+1)))
    if dof_per_node>=1:
        theta[i]=float(input("Inclination of element (in degrees) %d :" % int(i+1)))
        
for i in range(ele):
    if dof_per_node==1:
        k[i]=float(A[i]*E[i]/l[i])*np.array([[1,-1],[-1,1]]).astype(np.float)
    if dof_per_node==2:
        k[i]=float(A[i]*E[i]/l[i])*np.array([[ma.cos(ma.pi*theta[i]/180)**2,ma.cos(ma.pi*theta[i]/180)*ma.sin(ma.pi*theta[i]/180),-1*ma.cos(ma.pi*theta[i]/180)**2,-ma.cos(ma.pi*theta[i]/180)*ma.sin(ma.pi*theta[i]/180)],
                                             [ma.cos(ma.pi*theta[i]/180)*ma.sin(ma.pi*theta[i]/180),ma.sin(ma.pi*theta[i]/180)**2,-ma.cos(ma.pi*theta[i]/180)*ma.sin(ma.pi*theta[i]/180),-ma.sin(ma.pi*theta[i]/180)**2],
                                             [-ma.cos(ma.pi*theta[i]/180)**2,-ma.cos(ma.pi*theta[i]/180)*ma.sin(ma.pi*theta[i]/180),ma.cos(ma.pi*theta[i]/180)**2,ma.cos(ma.pi*theta[i]/180)*ma.sin(ma.pi*theta[i]/180)],
                                             [-ma.cos(ma.pi*theta[i]/180)*ma.sin(ma.pi*theta[i]/180),-ma.sin(ma.pi*theta[i]/180)**2,ma.cos(ma.pi*theta[i]/180)*ma.sin(ma.pi*theta[i]/180),ma.sin(ma.pi*theta[i]/180)**2]]).astype(np.float)
        


Number of elements in your problem:2
Number of nodes in your problem:3
Number of Fixed Nodes 2
Node number (Please provide fixed nodes in increasing order) 1
Node number (Please provide fixed nodes in increasing order) 3
Degrees of freedom per node 2
First node of element 
1 1
Last node of element 
1 2
First node of element 
2 2
Last node of element 
2 3
Area of element 
1 :4.908
Modulus of elasticity of element 1 :30e4
Length of element 
1 :144.2
Inclination of element (in degrees) 
1 :33.6
Area of element 
2 :4.908
Modulus of elasticity of element 2 :30e4
Length of element 
2 :80
Inclination of element (in degrees) 
2 :90


In [74]:
k

array([[[ 7.08383478e+03,  4.70648857e+03, -7.08383478e+03,
         -4.70648857e+03],
        [ 4.70648857e+03,  3.12698353e+03, -4.70648857e+03,
         -3.12698353e+03],
        [-7.08383478e+03, -4.70648857e+03,  7.08383478e+03,
          4.70648857e+03],
        [-4.70648857e+03, -3.12698353e+03,  4.70648857e+03,
          3.12698353e+03]],

       [[ 6.90076970e-29,  1.12698122e-12, -6.90076970e-29,
         -1.12698122e-12],
        [ 1.12698122e-12,  1.84050000e+04, -1.12698122e-12,
         -1.84050000e+04],
        [-6.90076970e-29, -1.12698122e-12,  6.90076970e-29,
          1.12698122e-12],
        [-1.12698122e-12, -1.84050000e+04,  1.12698122e-12,
          1.84050000e+04]]])

In [75]:
# assembly of Glbal stiffness matrix
K_global = np.zeros((nodes*dof_per_node,nodes*dof_per_node))


if dof_per_node==1:
    for i in range(ele):
        ind1=C[i]-1
        ind1=ind1.astype(int)
        K[ind1[0],ind1[0]]+=k[i][0][0]
        K[ind1[1],ind1[0]]+=k[i][1][0]
        K[ind1[0],ind1[1]]+=k[i][0][1]
        K[ind1[1],ind1[1]]+=k[i][1][1]
if dof_per_node==2:
    for e in range(ele):
        # Get the nodes for this element
        node = C[e]
        node=node.astype(int)
        node=node-1
        # Loop over each node in the element
        for i in range(len(node)):
            # Loop over each degree of freedom for node i
            for j in range(2):
                # Loop over each node in the element
                for b in range(len(node)):
                    # Loop over each degree of freedom for node k
                    for o in range(2):
                        # Add the corresponding element stiffness matrix term to the global stiffness matrix
                        K_global[2*node[i]+j, 2*node[b]+o] += k[e][2*i+j, 2*b+o]


In [76]:
K_global

array([[ 7.08383478e+03,  4.70648857e+03, -7.08383478e+03,
        -4.70648857e+03,  0.00000000e+00,  0.00000000e+00],
       [ 4.70648857e+03,  3.12698353e+03, -4.70648857e+03,
        -3.12698353e+03,  0.00000000e+00,  0.00000000e+00],
       [-7.08383478e+03, -4.70648857e+03,  7.08383478e+03,
         4.70648857e+03, -6.90076970e-29, -1.12698122e-12],
       [-4.70648857e+03, -3.12698353e+03,  4.70648857e+03,
         2.15319835e+04, -1.12698122e-12, -1.84050000e+04],
       [ 0.00000000e+00,  0.00000000e+00, -6.90076970e-29,
        -1.12698122e-12,  6.90076970e-29,  1.12698122e-12],
       [ 0.00000000e+00,  0.00000000e+00, -1.12698122e-12,
        -1.84050000e+04,  1.12698122e-12,  1.84050000e+04]])

In [78]:
#### Applying Boundary Conditions

K=K_global
K1=K.copy()
K_temp1=K1
if dof_per_node==1:
    for i in fix_n:
        print(i)
        K_temp1[i-1][:] = 0
        print(K_temp1)
        K_temp1.T[:][i-1] = 0
        print(K_temp1)

    # Select non-zero rows
    K_temp1 = K_temp1[~np.all(K_temp1 == 0, axis=1)]
    # Select non-zero columns
    K_temp1 = K_temp1[:, ~np.all(K_temp1 == 0, axis=0)]
    
if dof_per_node==2:
    for i in fix_n-1:
        print(i)
        K_temp1[2*i][:] = 0
        K_temp1[2*i+1][:] = 0
        print(K_temp1)
        K_temp1.T[:][2*i] = 0
        K_temp1.T[:][2*i+1] = 0
        print(K_temp1)
   

# Select non-zero rows
K_temp1 = K_temp1[~np.all(K_temp1 == 0, axis=1)]
#Select non-zero columns
K_temp1 = K_temp1[:, ~np.all(K_temp1 == 0, axis=0)]



0
[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [-7.08383478e+03 -4.70648857e+03  7.08383478e+03  4.70648857e+03
  -6.90076970e-29 -1.12698122e-12]
 [-4.70648857e+03 -3.12698353e+03  4.70648857e+03  2.15319835e+04
  -1.12698122e-12 -1.84050000e+04]
 [ 0.00000000e+00  0.00000000e+00 -6.90076970e-29 -1.12698122e-12
   6.90076970e-29  1.12698122e-12]
 [ 0.00000000e+00  0.00000000e+00 -1.12698122e-12 -1.84050000e+04
   1.12698122e-12  1.84050000e+04]]
[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  7.08383478e+03  4.70648857e+03
  -6.90076970e-29 -1.12698122e-12]
 [ 0.00000000e+00  0.00000000e+00  4.70648857e+03  2.15319835e+04
  -1.12698122e-12 -1.8

In [79]:
K_temp1

array([[ 7083.83477632,  4706.48857281],
       [ 4706.48857281, 21531.98353158]])

In [80]:
### Accepting force
F=np.zeros(nodes*dof_per_node)
for i in range(nodes):
    for j in range(dof_per_node):
        F[2*i+j]=float(input("Load at node %d and dof %d is :" % (int(i+1),int(j+1))))
F

Load at node 1 and dof 1 is :0
Load at node 1 and dof 2 is :0
Load at node 2 and dof 1 is :50
Load at node 2 and dof 2 is :0
Load at node 3 and dof 1 is :0
Load at node 3 and dof 2 is :0


array([ 0.,  0., 50.,  0.,  0.,  0.])

In [81]:
## 
if dof_per_node==1:
    F_temp1 = np.delete(F, list(fix_n-1))#Deleeting fixed nodes entires
if dof_per_node==2:
    F_temp1 = np.delete(F, np.array((2*(fix_n-1),2*np.array(fix_n-1)+1))) #Deleeting fixed nodes entries

In [82]:
F_temp1

array([50.,  0.])

In [83]:
## Solving for availabel degrees of freedom
x = np.linalg.solve(K_temp1,F_temp1)
u=np.zeros(nodes*dof_per_node)

g= [i for i in range(nodes) if i not in list(fix_n-1)]
for i in g:
    for j in range(len(x)-1):
        u[2*i]=x[j]
        u[2*i+1]=x[j+1]

In [85]:
u

array([ 0.        ,  0.        ,  0.00825752, -0.00180494,  0.        ,
        0.        ])

In [86]:
### Finding eleemntal quantities

if dof_per_node==1:
    sigma=np.zeros(ele)
    for i in range(ele):
        sigma[i]=(u[i+1]-u[i])/l[i]*E[i]
    R=np.dot(K,u)-F
    
###### Transfroming global findings to local settings to find elemental, deformations, stresses and loads
if dof_per_node==2:
    #finding displacement in local co-ordiates:
    u_loc=np.zeros((ele,2*dof_per_node))
    u_ele=np.zeros((ele,2*dof_per_node))
    for i in range(ele):
        u_loc_tran=np.array([[ma.cos(ma.pi*theta[i]/180),ma.sin(ma.pi*theta[i]/180),0,0],
                        [-ma.sin(ma.pi*theta[i]/180),ma.cos(ma.pi*theta[i]/180),0,0],
                       [0,0,ma.cos(ma.pi*theta[i]/180),ma.sin(ma.pi*theta[i]/180)],
                        [0,0,-ma.sin(ma.pi*theta[i]/180),ma.cos(ma.pi*theta[i]/180)]])
        nd=C[i]-1
        nd=nd.astype(int)
        v=0
        for j in nd:
            u_ele[i][2*v]=u[2*j]
            u_ele[i][2*v+1]=u[2*j+1]
            v+=1
        print(u_ele[i])
        u_loc[i]=np.dot(u_loc_tran,u_ele[i])


    
    


[ 0.          0.          0.00825752 -0.00180494]
[ 0.00825752 -0.00180494  0.          0.        ]


In [91]:
## Elemetnal forces
F_ele=np.zeros((ele,2*dof_per_node))
for i in range(ele):
    f_trans=float(A[i]*E[i]/l[i])*np.array([[1,0,-1,0],[0,0,0,0],[-1,0,1,0],[0,0,0,0]]).astype(np.float)
    F_ele[i]=np.dot(f_trans,u_loc[i])
    


4.908
300000.0


TypeError: 'int' object is not subscriptable

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [93]:
60.2/4.908


12.265688671556642

In [ ]:
## Elemetnal Stresses
sigma=np.zeros(ele)
for i in range(ele):
    sigma[i]=max(F_ele[i])/A[i]

In [ ]:
### Reactions at the support
R=np.dot(K,u)-F

In [66]:
u

array([ 0.        ,  0.        ,  0.00825752, -0.00180494,  0.        ,
        0.        ])

In [67]:
u_loc

array([[ 0.        ,  0.        ,  0.00587903, -0.00607302],
       [-0.00180494, -0.00825752,  0.        ,  0.        ]])

In [26]:
C[1]

array([2., 3.])

In [2]:
# Assembling whole code
ele=int(input('Number of elements in your problem:',))
nodes=int(input('Number of nodes in your problem:',))
n=int(input('Number of Fixed Nodes '))
fix_n=np.array([int(input('Node number (Please provide fixed nodes in increasing order) ')) for i in range(n)])
dof_per_node=int(input('Degrees of freedom per node '))
C=np.zeros((ele,2))
for i in range(ele):
    C[i][0]=int(input('First node of element %d ' % int(i+1) ))
    C[i][1]=int(input('Last node of element %d ' % int(i+1) ))
def solver1D2D(ele,nodes,n,fix_n,dof_per_node,C):
    A=np.zeros(ele)
    E=np.zeros(ele)
    l=np.zeros(ele)
    k=np.zeros((ele,2*dof_per_node,2*dof_per_node))
    F=np.zeros(nodes*dof_per_node)
    theta=np.zeros(ele)
    for i in range(ele):
        A[i]=float(input("Area of element %d :" % int(i+1)))
        E[i]=float(input("Modulus of elasticity of element %d :" % int(i+1)))
        l[i]=float(input("Length of element %d :" % int(i+1)))
        if dof_per_node>=1:
            theta[i]=float(input("Inclination of element (in degrees) %d :" % int(i+1)))
    for i in range(nodes):
        for j in range(dof_per_node):
            F[2*i+j]=float(input("Load at node %d and dof %d is :" % (int(i+1),int(j+1))))

    for i in range(ele):
        if dof_per_node==1:
            k[i]=float(A[i]*E[i]/l[i])*np.array([[1,-1],[-1,1]]).astype(np.float)
        if dof_per_node==2:
            k[i]=float(A[i]*E[i]/l[i])*np.array([[ma.cos(ma.pi*theta[i]/180)**2,ma.cos(ma.pi*theta[i]/180)*ma.sin(ma.pi*theta[i]/180),-1*ma.cos(ma.pi*theta[i]/180)**2,-ma.cos(ma.pi*theta[i]/180)*ma.sin(ma.pi*theta[i]/180)],
                                                 [ma.cos(ma.pi*theta[i]/180)*ma.sin(ma.pi*theta[i]/180),ma.sin(ma.pi*theta[i]/180)**2,-ma.cos(ma.pi*theta[i]/180)*ma.sin(ma.pi*theta[i]/180),-ma.sin(ma.pi*theta[i]/180)**2],
                                                 [-ma.cos(ma.pi*theta[i]/180)**2,-ma.cos(ma.pi*theta[i]/180)*ma.sin(ma.pi*theta[i]/180),ma.cos(ma.pi*theta[i]/180)**2,ma.cos(ma.pi*theta[i]/180)*ma.sin(ma.pi*theta[i]/180)],
                                                 [-ma.cos(ma.pi*theta[i]/180)*ma.sin(ma.pi*theta[i]/180),-ma.sin(ma.pi*theta[i]/180)**2,ma.cos(ma.pi*theta[i]/180)*ma.sin(ma.pi*theta[i]/180),ma.sin(ma.pi*theta[i]/180)**2]]).astype(np.float)
    # assembly of elements
    K_global = np.zeros((nodes*dof_per_node,nodes*dof_per_node))


    if dof_per_node==1:
        for i in range(ele):
            ind1=C[i]-1
            ind1=ind1.astype(int)
            K[ind1[0],ind1[0]]+=k[i][0][0]
            K[ind1[1],ind1[0]]+=k[i][1][0]
            K[ind1[0],ind1[1]]+=k[i][0][1]
            K[ind1[1],ind1[1]]+=k[i][1][1]
    if dof_per_node==2:
        for e in range(ele):
            # Get the nodes for this element
            node = C[e]
            node=node.astype(int)
            node=node-1
            # Loop over each node in the element
            for i in range(len(node)):
                # Loop over each degree of freedom for node i
                for j in range(2):
                    # Loop over each node in the element
                    for b in range(len(node)):
                        # Loop over each degree of freedom for node k
                        for o in range(2):
                            # Add the corresponding element stiffness matrix term to the global stiffness matrix
                            K_global[2*node[i]+j, 2*node[b]+o] += k[e][2*i+j, 2*b+o]

    K=K_global
    K1=K.copy()
    K_temp1=K1
    if dof_per_node==1:
        for i in fix_n:
            K_temp1[i-1][:] = 0
            K_temp1.T[:][i-1] = 0
            

        # Select non-zero rows
        K_temp1 = K_temp1[~np.all(K_temp1 == 0, axis=1)]
        # Select non-zero columns
        K_temp1 = K_temp1[:, ~np.all(K_temp1 == 0, axis=0)]

    if dof_per_node==2:
        for i in fix_n-1:
            K_temp1[2*i][:] = 0
            K_temp1[2*i+1][:] = 0
            K_temp1.T[:][2*i] = 0
            K_temp1.T[:][2*i+1] = 0

    # Select non-zero rows
    K_temp1 = K_temp1[~np.all(K_temp1 == 0, axis=1)]
    #Select non-zero columns
    K_temp1 = K_temp1[:, ~np.all(K_temp1 == 0, axis=0)]


    if dof_per_node==1:
        F_temp1 = np.delete(F, list(fix_n-1))#Deleeting fixed nodes entires
    if dof_per_node==2:
        F_temp1 = np.delete(F, np.array((2*(fix_n-1),2*np.array(fix_n-1)+1))) #Deleeting fixed nodes entries
    x = np.linalg.solve(K_temp1,F_temp1)
    u=np.zeros(nodes*dof_per_node)

    # if dof_per_node==2:
    g= [i for i in range(nodes) if i not in list(fix_n-1)]
    j=0
    for i in g:
        u[2*i]=x[2*j]
        u[2*i+1]=x[2*j+1]
        j+=1
    if dof_per_node==1:
        sigma=np.zeros(ele)
        for i in range(ele):
            sigma[i]=(u[i+1]-u[i])/l[i]*E[i]
        R=np.dot(K,u)-F



    if dof_per_node==2:
        #finding displacement in local co-ordiates:
        u_loc=np.zeros((ele,2*dof_per_node))
        u_ele=np.zeros((ele,2*dof_per_node))
        for i in range(ele):
            u_loc_tran=np.array([[ma.cos(ma.pi*theta[i]/180),ma.sin(ma.pi*theta[i]/180),0,0],
                            [-ma.sin(ma.pi*theta[i]/180),ma.cos(ma.pi*theta[i]/180),0,0],
                           [0,0,ma.cos(ma.pi*theta[i]/180),ma.sin(ma.pi*theta[i]/180)],
                            [0,0,-ma.sin(ma.pi*theta[i]/180),ma.cos(ma.pi*theta[i]/180)]])
            nd=C[i]-1
            nd=nd.astype(int)
            v=0
            for j in nd:
                u_ele[i][2*v]=u[2*j]
                u_ele[i][2*v+1]=u[2*j+1]
                v+=1
            u_loc[i]=np.dot(u_loc_tran,u_ele[i])

    F_ele=np.zeros((ele,2*dof_per_node))
    for i in range(ele):
        f_trans=float(A[i]*E[i]/l[i])*np.array([[1,0,-1,0],[0,0,0,0],[-1,0,1,0],[0,0,0,0]]).astype(np.float)
        F_ele[i]=np.dot(f_trans,u_loc[i])

    sigma=np.zeros(ele)
    for i in range(ele):
        sigma[i]=min(F_ele[i])/A[i]
    R=np.dot(K,u)-F




    print('The global stiffness matrix is ',K_global)
    print('Forces in the elements are ', F_ele)
    print('The nodal displacements are ',u)
    print('The elemental stresses are ',sigma)
    print('The reactions at the nodes are ', R)
    
    return

Number of elements in your problem:6
Number of nodes in your problem:4
Number of Fixed Nodes 2
Node number (Please provide fixed nodes in increasing order) 1
Node number (Please provide fixed nodes in increasing order) 4
Degrees of freedom per node 2
First node of element 
1 1
Last node of element 
1 2
First node of element 
2 1
Last node of element 
2 3
First node of element 
3 2
Last node of element 
3 4
First node of element 
4 2
Last node of element 
4 3
First node of element 
5 3
Last node of element 
5 4
First node of element 
6 1
Last node of element 
6 4


In [3]:
solver1D2D(ele,nodes,n,fix_n,dof_per_node,C)

Area of element 
1 :1
Modulus of elasticity of element 1 :10e6
Length of element 
1 :20
Inclination of element (in degrees) 
1 :180
Area of element 
2 :1
Modulus of elasticity of element 2 :10e6
Length of element 
2 :25
Inclination of element (in degrees) 
2 :36.87
Area of element 
3 :1
Modulus of elasticity of element 3 :10e6
Length of element 
3 :25
Inclination of element (in degrees) 
3 :143.13
Area of element 
4 :1
Modulus of elasticity of element 4 :10e6
Length of element 
4 :15
Inclination of element (in degrees) 
4 :90
Area of element 
5 :1
Modulus of elasticity of element 5 :10e6
Length of element 
5 :20
Inclination of element (in degrees) 
5 :180
Area of element 
6 :1
Modulus of elasticity of element 6 :10e6
Length of element 
6 :15
Inclination of element (in degrees) 
6 :90
Load at node 1 and dof 1 is :0
Load at node 1 and dof 2 is :0
Load at node 2 and dof 1 is :0
Load at node 2 and dof 2 is :1000
Load at node 3 and dof 1 is :0
Load at node 3 and dof 2 is :1000
Load at node 

# For 3 D arrangements

In [1]:
import numpy as np

import math as ma

# Define input parameters
nodes = 10  # number of nodes
ele = 25  # number of elements
area = 3.142  # cross-sectional area of truss members (m^2)
youngs_modulus = 3e7  # Young's modulus of material (Pa)
rho = 7.3e-4  # density of material (kg/m^3)
nu = 0.3  # Poisson's ratio
# n=int(input('Number of Fixed Nodes '))
# fix_n=np.array([int(input('Node number (Please provide fixed nodes in increasing order) ')) for i in range(n)])
dof_per_node=int(input('Degrees of freedom per node '))
# Define element connectivity and nodal coordinates
# C= np.array([[1, 4], [2, 4], [3, 4]])
C=np.array([[1,2],[1,4],[2,3],[1,5],[2,6],[2,4],[2,5],[1,3],[1,6],[3,6],[4,5],[3,4],[5,6],[3,10],[6,7],[4,9],[5,8],[4,7],[3,8],[5,10],[6,9],[6,10],[3,7],[4,8],[5,9]])
# node_coords = np.array([[0, 0, 0], [0, -1, 1], [0, 1, 1], [1, 0, 1]])
# node_coords=np.array([[2.5,4,8],[5.5,4,8],[2.5,5.5,4],[5.5,5.5,4],[5.5,2.5,4],[2.5,2.5,4],[0,8,0],[8,8,0],[8,0,0],[0,0,0]])
node_coords=np.array([[-1.5,0,8],[1.5,0,8],[-1.5,1.5,4],[1.5,1.5,4],[1.5,-1.5,4],[-1.5,-1.5,4],[-4,4,0],[4,4,0],[4,-4,0],[-4,-4,0]])
# *12
# Initialize local stiffness matrix

k=np.zeros((ele,dof_per_node*2, dof_per_node*2)) ## matrix of local 
for i in range(ele):
    # Extract nodal coordinates and element length for current element
    n1 = C[i, 0] - 1
    n2 = C[i, 1] - 1
    x1, y1, z1 = node_coords[n1]
    x2, y2, z2 = node_coords[n2]
    L = np.sqrt((x2 - x1)**2 + (y2 - y1)**2 + (z2 - z1)**2)
    b=np.array([[x2 - x1],[y2 - y1],[z2 - z1]])

    M=youngs_modulus*area/L*np.array([[1,-1],[-1,1]])

    n=b.T/L
    G = np.block([[n, np.zeros_like(n)],
              [np.zeros_like(n), n]])

    
    
    # Compute element stiffness matrix in global coordinates
#     k[i] = np.transpose(T) @ k_elem @ T #@ nu_mat
    k[i] = np.transpose(G) @ M @ G #@ nu_mat

Degrees of freedom per node 3


In [2]:
# assembly of Glbal stiffness matrix
K_global = np.zeros((nodes*dof_per_node,nodes*dof_per_node))

if dof_per_node==1:
    for i in range(ele):
        ind1=C[i]-1
        ind1=ind1.astype(int)
        K[ind1[0],ind1[0]]+=k[i][0][0]
        K[ind1[1],ind1[0]]+=k[i][1][0]
        K[ind1[0],ind1[1]]+=k[i][0][1]
        K[ind1[1],ind1[1]]+=k[i][1][1]
if dof_per_node==3:
    
    for e in range(ele):
#         print('elee')
        # Get the nodes for this element
        node = C[e]
        node=node.astype(int)
        node=node-1
        # Loop over each node in the element
        for i in range(len(node)):
            # Loop over each degree of freedom for node i
            for j in range(3):
                # Loop over each node in the element
                for b in range(len(node)):
#                     print('b')
                    # Loop over each degree of freedom for node k
                    for o in range(3):
                        # Add the corresponding element stiffness matrix term to the global stiffness matrix
#                         print([3*node[i]+j, 3*node[b]+o],'=',[e],[3*i+j, 3*b+o])
                        K_global[3*node[i]+j, 3*node[b]+o] += k[e][3*i+j, 3*b+o]
                        


In [3]:
K_global

array([[ 4.33475207e+07,  0.00000000e+00, -1.59033610e+07,
        -3.14200000e+07,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        -5.96376037e+06, -2.98188019e+06,  7.95168050e+06,
        -5.96376037e+06,  2.98188019e+06,  7.95168050e+06,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  8.42246577e+06,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00, -2.72029279e+06,  7.25411411e+06,
        -2.98188019e+06, -1.49094009e+06,  3.97584025e+06,
         2.98188019e+06, -1.49094009e+06, -3.97584025e+06,
         0.00000000e+00, -2.72029279e+06, -7.25411411e+06,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+

In [4]:
n=int(input('Number of Fixed Nodes '))
fix_n=np.array([int(input('Node number (Please provide fixed nodes in increasing order) ')) for i in range(n)])

Number of Fixed Nodes 4
Node number (Please provide fixed nodes in increasing order) 7
Node number (Please provide fixed nodes in increasing order) 8
Node number (Please provide fixed nodes in increasing order) 9
Node number (Please provide fixed nodes in increasing order) 10


In [5]:
#### Applying Boundary Conditions

K=K_global
K1=K.copy()
K_temp1=K1
if dof_per_node==1:
    for i in fix_n:
        print(i)
        K_temp1[i-1][:] = 0
        print(K_temp1)
        K_temp1.T[:][i-1] = 0
        print(K_temp1)

    # Select non-zero rows
    K_temp1 = K_temp1[~np.all(K_temp1 == 0, axis=1)]
    # Select non-zero columns
    K_temp1 = K_temp1[:, ~np.all(K_temp1 == 0, axis=0)]
    
if dof_per_node==3:
      for i in fix_n-1:
            K_temp1[3*i][:] = 0
            K_temp1[3*i+1][:] = 0
            K_temp1[3*i+2][:] = 0
            K_temp1.T[:][3*i] = 0
            K_temp1.T[:][3*i+1] = 0
            K_temp1.T[:][3*i+2] = 0
        
# Select non-zero rows
K_temp1 = K_temp1[~np.all(K_temp1 == 0, axis=1)]
#Select non-zero columns
K_temp1 = K_temp1[:, ~np.all(K_temp1 == 0, axis=0)]


In [6]:
K_global

array([[ 4.33475207e+07,  0.00000000e+00, -1.59033610e+07,
        -3.14200000e+07,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        -5.96376037e+06, -2.98188019e+06,  7.95168050e+06,
        -5.96376037e+06,  2.98188019e+06,  7.95168050e+06,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  8.42246577e+06,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00, -2.72029279e+06,  7.25411411e+06,
        -2.98188019e+06, -1.49094009e+06,  3.97584025e+06,
         2.98188019e+06, -1.49094009e+06, -3.97584025e+06,
         0.00000000e+00, -2.72029279e+06, -7.25411411e+06,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+

In [7]:
K_temp1

array([[ 4.33475207e+07,  0.00000000e+00, -1.59033610e+07,
        -3.14200000e+07,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        -5.96376037e+06, -2.98188019e+06,  7.95168050e+06,
        -5.96376037e+06,  2.98188019e+06,  7.95168050e+06,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  8.42246577e+06,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00, -2.72029279e+06,  7.25411411e+06,
        -2.98188019e+06, -1.49094009e+06,  3.97584025e+06,
         2.98188019e+06, -1.49094009e+06, -3.97584025e+06,
         0.00000000e+00, -2.72029279e+06, -7.25411411e+06],
       [-1.59033610e+07,  0.00000000e+00,  5.98930899e+07,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  7.25411411e+06, -1.93443043e+07,
         7.95168050e+06,  3.97584025e+06, -1.06022407e+07,
         7.95168050e+06, -3.97584025e+06, -1.06022407e

In [8]:
### Accepting force
F=np.zeros(nodes*dof_per_node)
for i in range(nodes):
    for j in range(dof_per_node):
        F[3*i+j]=float(input("Load at node %d and dof %d is :" % (int(i+1),int(j+1))))

Load at node 1 and dof 1 is :0
Load at node 1 and dof 2 is :60e3
Load at node 1 and dof 3 is :0
Load at node 2 and dof 1 is :0
Load at node 2 and dof 2 is :60e3
Load at node 2 and dof 3 is :0
Load at node 3 and dof 1 is :0
Load at node 3 and dof 2 is :0
Load at node 3 and dof 3 is :0
Load at node 4 and dof 1 is :0
Load at node 4 and dof 2 is :0
Load at node 4 and dof 3 is :0
Load at node 5 and dof 1 is :00
Load at node 5 and dof 2 is :0
Load at node 5 and dof 3 is :0
Load at node 6 and dof 1 is :0
Load at node 6 and dof 2 is :0
Load at node 6 and dof 3 is :0
Load at node 7 and dof 1 is :0
Load at node 7 and dof 2 is :0
Load at node 7 and dof 3 is :0
Load at node 8 and dof 1 is :0
Load at node 8 and dof 2 is :0
Load at node 8 and dof 3 is :0
Load at node 9 and dof 1 is :0
Load at node 9 and dof 2 is :0
Load at node 9 and dof 3 is :0
Load at node 10 and dof 1 is :0
Load at node 10 and dof 2 is :0
Load at node 10 and dof 3 is :0


In [9]:
## 
if dof_per_node==1:
    F_temp1 = np.delete(F, list(fix_n-1))#Deleeting fixed nodes entires
if dof_per_node==2:
    F_temp1 = np.delete(F, np.array((2*(fix_n-1),2*np.array(fix_n-1)+1))) #Deleeting fixed nodes entries
if dof_per_node==3:
    F_temp1 = np.delete(F, np.array((3*(fix_n-1),3*np.array(fix_n-1)+1,3*np.array(fix_n-1)+2))) #Deleeting fixed nodes entries

In [10]:
F_temp1

array([    0., 60000.,     0.,     0., 60000.,     0.,     0.,     0.,
           0.,     0.,     0.,     0.,     0.,     0.,     0.,     0.,
           0.,     0.])

In [11]:
## Solving for availabel degrees of freedom
x = np.linalg.solve(K_temp1,F_temp1)
u=np.zeros(nodes*dof_per_node)

g= [i for i in range(nodes) if i not in list(fix_n-1)]
j=0
for i in g:
        u[3*i]=x[3*j]      
        u[3*i+1]=x[3*j+1]
        u[3*i+2]=x[3*j+2]
        j+=1

In [12]:
u

array([ 8.37818981e-19,  1.97885194e-02,  1.25314575e-19,  8.12340376e-19,
        1.97885194e-02, -5.56079705e-19, -1.44068339e-04,  1.30216381e-03,
       -4.22270231e-03,  1.44068339e-04,  1.30216381e-03, -4.22270231e-03,
       -1.44068339e-04,  1.30216381e-03,  4.22270231e-03,  1.44068339e-04,
        1.30216381e-03,  4.22270231e-03,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00])

In [13]:
x

array([ 8.37818981e-19,  1.97885194e-02,  1.25314575e-19,  8.12340376e-19,
        1.97885194e-02, -5.56079705e-19, -1.44068339e-04,  1.30216381e-03,
       -4.22270231e-03,  1.44068339e-04,  1.30216381e-03, -4.22270231e-03,
       -1.44068339e-04,  1.30216381e-03,  4.22270231e-03,  1.44068339e-04,
        1.30216381e-03,  4.22270231e-03])

In [15]:
### Finding eleemntal quantities

if dof_per_node==1:
    sigma=np.zeros(ele)
    for i in range(ele):
        sigma[i]=(u[i+1]-u[i])/l[i]*E[i]
    R=np.dot(K,u)-F
    
###### Transfroming global findings to local settings to find elemental, deformations, stresses and loads
if dof_per_node==3:
    sigma=np.zeros(ele)
    F_ele=np.zeros((ele,2*dof_per_node))
    #finding displacement in local co-ordiates:
    u_loc=np.zeros((ele,2*dof_per_node))
    u_ele=np.zeros((ele,2*dof_per_node))
    for i in range(ele):
        # Extract nodal coordinates and element length for current element
        n1 = C[i, 0] - 1
        n2 = C[i, 1] - 1
        x1, y1, z1 = node_coords[n1]
        x2, y2, z2 = node_coords[n2]
        L = np.sqrt((x2 - x1)**2 + (y2 - y1)**2 + (z2 - z1)**2)
        b=np.array([[x2 - x1],[y2 - y1],[z2 - z1]])

        # Define the transformation matrix
        n=b.T/L
        G = np.block([[n, np.zeros_like(n)],
              [np.zeros_like(n), n]])

        # Calculate the transformation matrix
#         T = transformation_matrix(theta)
        # Calculate the local displacement vector 
        nd=C[i]-1
        nd=nd.astype(int)
        v=0
        for j in nd:
            u_ele[i][3*v]=u[3*j]
            u_ele[i][3*v+1]=u[3*j+1]
            u_ele[i][3*v+2]=u[3*j+2]
            v+=1
#         u_loc[i]=np.dot(T, u_ele[i])
#         u_loc[i]=np.dot(u_loc_tran,u_ele[i])
        F_ele[i]=np.dot(np.dot(np.array([-1,1]),G),u_ele[i])*youngs_modulus*area/L
        sigma[i]=min(F_ele[i])/area
    
        

In [252]:
# np.dot(u_loc[3],T)



In [16]:
u_ele

array([[ 8.37818981e-19,  1.97885194e-02,  1.25314575e-19,
         8.12340376e-19,  1.97885194e-02, -5.56079705e-19],
       [ 8.37818981e-19,  1.97885194e-02,  1.25314575e-19,
         1.44068339e-04,  1.30216381e-03, -4.22270231e-03],
       [ 8.12340376e-19,  1.97885194e-02, -5.56079705e-19,
        -1.44068339e-04,  1.30216381e-03, -4.22270231e-03],
       [ 8.37818981e-19,  1.97885194e-02,  1.25314575e-19,
        -1.44068339e-04,  1.30216381e-03,  4.22270231e-03],
       [ 8.12340376e-19,  1.97885194e-02, -5.56079705e-19,
         1.44068339e-04,  1.30216381e-03,  4.22270231e-03],
       [ 8.12340376e-19,  1.97885194e-02, -5.56079705e-19,
         1.44068339e-04,  1.30216381e-03, -4.22270231e-03],
       [ 8.12340376e-19,  1.97885194e-02, -5.56079705e-19,
        -1.44068339e-04,  1.30216381e-03,  4.22270231e-03],
       [ 8.37818981e-19,  1.97885194e-02,  1.25314575e-19,
        -1.44068339e-04,  1.30216381e-03, -4.22270231e-03],
       [ 8.37818981e-19,  1.97885194e-02,  1.253

In [17]:
F_ele

array([[-8.00537756e-13, -8.00537756e-13, -8.00537756e-13,
        -8.00537756e-13, -8.00537756e-13, -8.00537756e-13],
       [-3.59970091e+04, -3.59970091e+04, -3.59970091e+04,
        -3.59970091e+04, -3.59970091e+04, -3.59970091e+04],
       [-3.59970091e+04, -3.59970091e+04, -3.59970091e+04,
        -3.59970091e+04, -3.59970091e+04, -3.59970091e+04],
       [ 3.59970091e+04,  3.59970091e+04,  3.59970091e+04,
         3.59970091e+04,  3.59970091e+04,  3.59970091e+04],
       [ 3.59970091e+04,  3.59970091e+04,  3.59970091e+04,
         3.59970091e+04,  3.59970091e+04,  3.59970091e+04],
       [-5.59812682e+04, -5.59812682e+04, -5.59812682e+04,
        -5.59812682e+04, -5.59812682e+04, -5.59812682e+04],
       [ 5.59812682e+04,  5.59812682e+04,  5.59812682e+04,
         5.59812682e+04,  5.59812682e+04,  5.59812682e+04],
       [-5.59812682e+04, -5.59812682e+04, -5.59812682e+04,
        -5.59812682e+04, -5.59812682e+04, -5.59812682e+04],
       [ 5.59812682e+04,  5.59812682e+04,  5.598

In [18]:
sigma

array([-2.54786046e-13, -1.14567184e+04, -1.14567184e+04,  1.14567184e+04,
        1.14567184e+04, -1.78170809e+04,  1.78170809e+04, -1.78170809e+04,
        1.78170809e+04,  2.16840434e-12,  2.16840434e-12,  2.88136677e+03,
       -2.88136677e+03, -5.76518808e+03,  5.76518808e+03, -5.76518808e+03,
        5.76518808e+03, -1.10593388e+04, -1.10593388e+04,  1.10593388e+04,
        1.10593388e+04,  2.15856733e+04, -2.15856733e+04, -2.15856733e+04,
        2.15856733e+04])

In [19]:
def check_symmetric(a, rtol=1e-05, atol=1e-08):
    return np.allclose(a, a.T, rtol=rtol, atol=atol)

In [20]:
check_symmetric(K_global, rtol=1e-05, atol=1e-08)

True

1.1670934699103712